<?php
// $Id$ 

/**
 * @file 
 */

/**
 * Implementation of hook_block() 
 */
function my_splash_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
    case 'list':

    case 'view':

    case 'configure':

    case 'save':

  }
}

/**
 * Implementation of hook_help() 
 */
function my_splash_help($path, $arg) {

}

/**
 * Implementation of hook_page_alter
 */
function my_splash_page_alter(&$page){
  if(isset($_COOKIE["MySplash"]) && $_COOKIE["MySplash"] == 1) return true;
  drupal_add_css(drupal_get_path('module', 'my_splash') . "/css/ui-lightness/jquery-ui.custom.css", array('preprocess' => FALSE));
  drupal_add_js(create_box(), 'inline');
  $msg = variable_get("my_splash_msg", "Bienvenu(e)");
  $title = variable_get("my_splash_title", "Bienvenu(e)");
  $page['page_bottom'][] = array(
    '#weight' => -10, 
    '#markup' => "<div id=\"dialog-message\" title=\"$title\">
	<p>
		$msg
	</p>
</div>",
  );
  setcookie("MySplash", 1, time()+3600*24);
}



function create_box(){
  $width = variable_get("my_splash_width", "400");
  $height = variable_get("my_splash_height", "250");
  $script = "jQuery(function() {
		jQuery( \"#dialog:ui-dialog\" ).dialog( \"destroy\" );
	
		jQuery( \"#dialog-message\" ).dialog({
			modal: true,
            width:$width,
            height:$height,
			buttons: {
				Ok: function() {
					jQuery( this ).dialog( \"close\" );
				}
			}
		});
	});";
  return $script;
}


function my_splash_admin() {
  $form = array();

   $form['my_splash_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Box title'),
    '#default_value' => variable_get('my_splash_title', 'Bienvenu(e)'),
    '#size' => 80,
    '#max' => 200,
    '#required' => TRUE,
  );
   
  $form['my_splash_msg'] = array(
    '#type' => 'textarea',
    '#title' => t('Message to display'),
    '#default_value' => variable_get('my_splash_msg', 'Bienvenu(e)'),
    '#cols' => 80,
    '#rows' => 20,
    '#description' => t("Message to display"),
    '#required' => TRUE,
    '#class'=>'tinymce',
  );
  
  $form['my_splash_width'] = array(
    '#type' => 'textfield',
    '#title' => t('Box width'),
    '#default_value' => variable_get('my_splash_width', '400'),
    '#size' => 3,
    '#max' => 3,
    '#required' => FALSE,
  );
  
  $form['my_splash_height'] = array(
    '#type' => 'textfield',
    '#title' => t('Box width'),
    '#default_value' => variable_get('my_splash_height', '250'),
    '#size' => 3,
    '#max' => 3,
    '#required' => FALSE,
  );

  return system_settings_form($form);
}

function my_splash_menu() {

  $items = array();

  $items['admin/settings/my_splash'] = array(
    'title' => t('Splash message'),
    'description' => t('Settings for Splash message'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('my_splash_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}